name: nearby_helper_app
description: "Nearby Helper App - Find and connect with nearby helpers easily."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1

  # Networking
  http: ^1.2.2

  # Location & Maps
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0

  # Permissions & Storage
  permission_handler: ^11.3.1
  path_provider: ^2.1.4

  # State Management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # - assets/icons/
    #- assets/images/
